### ISSUE TITLE
interest in contributing to Java port

### ISSUE THREAD

**Issue by williwambu** [pluspeople/pesaPi#4]
I would like to contribute to the Java port of pesaPi. The java port is in very early stages and has not reached production stage hence I feel obliged to contribute.

**Comment by pluspeople** [comment]
great - code contributions are always welcome.. 
Kindly use the PesaPi mailling list for discussions if you need any help getting started.

**Comment by williwambu** [comment]
How would you like us to proceed?

**Comment by pluspeople** [comment]
Generally use the google group to communicate as I rarely check this spot.

However best way to proceed is to either fork the project and start pushing back some pull requests, or if needed get in touch (directly) and we can sit down and discuss whats the be areas to work on are.
