### ISSUE TITLE
create the ruby port

### ISSUE THREAD

**Issue by leonardk1** [pluspeople/pesaPi#5]
I am  a ruby developer and am interested in creating the ruby port

**Comment by leonardk1** [comment]
@pluspeople I'd like to know the basic things am supposed to know so that I develop the ruby port

**Comment by pluspeople** [comment]
great - code contributions are always welcome..
Best place to start would probably be to read the php code and understand the structure of it to make it easier to port.
Kindly use the PesaPi mailling list for discussions if you need any help getting started.
