### ISSUE TITLE
Amount entered in database is wrong.

### ISSUE THREAD

**Issue by muas19** [pluspeople/pesaPi#8]
Tested a payment of ksh. 10 to my till number but the amount entered in the database was 1000. Also if the amount in the till is 35, the db read 3500.

**Comment by pluspeople** [comment]
All amounts in PesaPi is entered as the mimimum currency unit. in Kenya this means cents, so 3500 cents is 35 shilling.
In other words - this is intentional and how the system is supposed to work.

**Comment by muas19** [comment]
Good. Will mark it as closed. But it would be wiser to disclose that info beforehand.
